// Generated by CoffeeScript 1.6.3
jasmine.getFixtures().fixturesPath = '/absolute/Users/james/Projects/Selectr/test/fixtures';

describe("Selectr", function() {
  beforeEach(function() {
    loadFixtures('SelectElement.html');
    this.select = $("select");
    return this.instance = $("select").selectr();
  });
  afterEach(function() {
    this.select = null;
    return this.instance = null;
  });
  it("should be chainable", function() {
    return expect(this.instance).toEqual(this.select);
  });
  describe("options", function() {
    return it("should contain default options", function() {
      return expect($.fn.selectr.defaultOptions).toBeDefined();
    });
  });
  return describe("UI setup", function() {
    it("should hide the original input", function() {
      return expect(this.select).toBeHidden();
    });
    return describe("wrapper", function() {
      beforeEach(function() {
        return this.wrap = this.select.siblings(".selectr-wrap");
      });
      afterEach(function() {
        return this.wrap = null;
      });
      it("should be a sibling to the original select", function() {
        return expect(this.wrap).toExist();
      });
      it("should have the class \"selectr-wrap\"", function() {
        return expect(this.wrap).toHaveClass("selectr-wrap");
      });
      return it("should have a width based on settings", function() {});
    });
  });
});
